config/routes.rb
Rails.application.routes.draw do
  # usuarios y log in
  devise_for :users
  get 'user/log_in'
  get 'user/log_in_as_user'
  get 'user/log_out'
  get 'user/sin_permisos'
  post 'externo', to: 'user#externo'
  get 'user/authenticated'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'documentos/descargar', to: 'documentos#descargar'
  resources :documentos

  get 'favoritos', to: 'favoritos#show'
  post 'add_favorito', to: 'documentos#add_favorite'
  post 'remove_favorito', to: 'documentos#remove_favorite'

  get 'admin', to: 'admin#index'
  get 'admin/usuarios', to: 'admin#index', :as => 'admin_usuarios'
  get 'admin/tipos', to: 'admin#index', :as => 'admin_tipos'
  get 'admin/areas', to: 'admin#index', :as => 'admin_areas'
  get 'admin/actividad', to: 'admin#index', :as => 'admin_actividad'

  post 'admin/create_tipo', to: 'admin#create_tipo'
  post 'admin/update_tipo', to: 'admin#update_tipo'
  post 'admin/delete_tipo', to: 'admin#delete_tipo'

  post 'admin/create_area', to: 'admin#create_area'
  post 'admin/update_area', to: 'admin#update_area'
  post 'admin/delete_area', to: 'admin#delete_area'

  post 'admin/update_usuario', to: 'admin#update_usuario'
  get 'home', to: 'home#index'

  get 'search/advanced', to: 'busquedas#advanced'
  get 'results', to: 'busquedas#search'
  get 'search', to: 'busquedas#normal_search'

  post 'delete', to: 'documentos#delete'
  post 'edit', to: 'documentos#edit'
  post 'rewrite', to: 'documentos#rewrite'

  # Es necesario que la root esté seteada para el tema de usuarios
  root to: "home#index"
end

app/models/documento.rb
class Documento < ApplicationRecord
  belongs_to :tipo_documento
  belongs_to :user
  has_many :documento_tiene_areas
  has_many :areas, through: :documento_tiene_areas
  has_many :documento_tiene_tags
  has_many :tags, through: :documento_tiene_tags
  has_many :user_descarga_documentos
  has_many :users_que_han_descargado, through: :user_descarga_documentos, source: :user
  mount_uploader :archivo_documento, DocumentoUploader
  validates_integrity_of :archivo_documento
  has_paper_trail
  validates :titulo, presence: true
  validates :archivo_documento, presence: true
  validates :tipo_documento_id, presence: true
end

app/controllers/documentos_controller.rb
class DocumentosController < ApplicationController
  before_action :permiso_subir_documento, only: [:new, :create]
  before_action :permiso_modificar_data, only: [:edit]
  before_action :permiso_eliminar_archivo, only: [:delete]
  before_action :permiso_sobreescribir_archivo, only: [:rewrite]
  before_action :documento_esta_activo_show, only: [:show]
  before_action :documento_esta_activo_accion, only: [:edit, :rewrite, :delete]

  def index
    redirect_to search_path+"?title="
  end

  def new
    @document = Documento.new
    @tipos = TipoDocumento.all
    @areas = Area.all
  end

  def show
    @document = Documento.find(params[:id])
    @tipo= TipoDocumento.find(@document.tipo_documento_id)
  end

  def descargar
    @documento = Documento.find(params[:data])
    if not @documento.activo
      flash[:alert] = "Este documento ya no está disponible."
      redirect_to root_path
    else
      ruta = @documento.archivo_documento
      descarga = UserDescargaDocumento.new
      descarga.user_id = current_user.id
      descarga.documento_id = params[:data]
      descarga.save!
      filename = Zaru.sanitize! @documento.titulo
      if @documento.extension.present?
        filename = filename + "." + Zaru.sanitize!(@documento.extension)
      end
      if not filename.present?
        filename = "file"
      end
      send_file ruta.path, filename: filename
    end
  end

  def create
    @user = current_user
    @document = Documento.new
    @document.user_id = @user.id
    @document.titulo=params[:title]
    @document.descripcion=params[:descripcion]
    @document.autor = params[:autor]
    begin
      @document.fecha_documento = DateTime.strptime(params[:fecha], '%d/%m/%Y')
    rescue
    end
    @document.fecha_subida = DateTime.now
    @document.created_at = DateTime.now
    @document.updated_at = DateTime.now
    @document.tipo_documento_id = params[:tipo]
    @areas_a_agregar = Area.where(id: params[:areas])
    @document.areas << @areas_a_agregar
    @document.archivo_documento = params[:file]
    @document.peso = File.size(params[:file].tempfile)
    if params[:file].content_type == "application/octet-stream"
      ext = ""
    else
      ext = Rack::Mime::MIME_TYPES.invert[params[:file].content_type]
      if not ext.present?
        ext = ""
      end
      begin
        ext = ext.gsub(".", "").upcase
      rescue        
      end
    end
    if ext.length > 50
      ext = ext[0..49]
    end
    @document.extension = ext
    if not @document.save
      flash[:alert] = "Error. Chequea el tamaño del archivo y los demás parámetros."
      redirect_to new_documento_path
    else
      redirect_to @document
    end
  end

  def edit
    @document = Documento.find(params[:document][:id])
    @document.update(document_params)
    @areas = params[:document][:area_ids]
    @document.update_attribute(:area_ids, @areas)
    redirect_to @document, notice: 'Documento exitosamente editado'
  end

  def rewrite
    old_id = params[:document][:id]
    new_file = params[:file]
    user = current_user
    old_doc = Documento.find(old_id)
    new_doc = Documento.new
    new_doc.titulo = old_doc.titulo
    new_doc.descripcion = old_doc.descripcion
    new_doc.autor = old_doc.autor
    new_doc.fecha_documento = old_doc.fecha_documento
    new_doc.tipo_documento = old_doc.tipo_documento
    new_doc.areas = old_doc.areas
    new_doc.user_id = user.id
    new_doc.archivo_documento = new_file
    new_doc.peso = File.size(new_file.tempfile)
    ext = Rack::Mime::MIME_TYPES.invert[params[:file].content_type]
    ext = ext.gsub(".", "").upcase
    if ext.length > 50
      ext = ext[0..49]
    end
    new_doc.extension = ext
    new_doc.fecha_subida = DateTime.now
    if new_doc.save
      old_doc.update_attributes(:activo => false, :sobreescrito => true )
      redirect_to new_doc, notice: 'Documento exitosamente actualizado'
    else
      flash[:alert] = "Error. Chequea el tamaño e integridad del archivo."
      redirect_to old_doc
    end
  end

  def delete
    document = Documento.find(params[:document][:id])
    document.update_attribute(:activo, false)
    redirect_to home_path, notice: 'Documento eliminado'
  end

  def add_favorite
    @favorito = Favorito.new
    @favorito.user_id = current_user.id
    @favorito.documento_id = params[:id]
    @favorito.created_at = DateTime.now
    @favorito.updated_at = DateTime.now
    @favorito.save
    render json: {ok:true}
  end

  def remove_favorite
    @favorito = Favorito.where(user_id: current_user.id, documento_id: params[:id]).take!
    @favorito.destroy
    render json: {ok:true}
  end

  private
    def document_params
      params.require(:document).permit(:titulo, :descripcion, :tipo_documento_id, :autor, :fecha_documento)
    end

    def permiso_subir_documento
      if not current_user.puede_subir_archivos?
        unauthorized
      end
    end
    def permiso_modificar_data
      if not current_user.puede_modificar_data?
        unauthorized
      end
    end
    def permiso_eliminar_archivo
      if not current_user.puede_eliminar_archivos?
        unauthorized
      end
    end
    def permiso_sobreescribir_archivo
      if not current_user.puede_sobreescribir_archivos?
        unauthorized
      end
    end
    def documento_esta_activo_show
      document = Documento.find(params[:id])
      if not document.activo
        flash[:alert] = "Este documento ya no está disponible."
        redirect_to root_path
      end
    end
    def documento_esta_activo_accion
      document = Documento.find(params[:document][:id])
      if not document.activo
        flash[:alert] = "Este documento ya no está disponible."
        redirect_to root_path
      end
    end
end

app/views/documentos/index.html.haml
.container  
  .row.justify-content-md-center
    %h1 Resultados de búsqueda
  .row
    %a{:href => ""} Descargar seleccionados
  .row
    %table.table.table-hover
      %thead
        %tr
          %th
          %th
          %th{:scope => "col"} Nombre
          %th{:scope => "col"} Fecha de subida
          %th{:scope => "col"} Tamaño
          %th{:scope => "col"} Subido por
          %th{:scope => "col"} Tipo
          %th{:scope => "col"} Áreas
          %th{:scope => "col"} Extensión
          %th{:scope => "col"}
      %tbody
        - @documentos.each do |documento|
          %tr.clickable-row{"data-href" => "/documentos/"+String(documento.id)}
            %th
              .form-check
                %input#defaultCheck1.form-check-input{:type => "checkbox", :value => ""}/
                -#%label.form-check-label{:for => "defaultCheck1"}
            %td
              - if documento.extension=="PDF"
                =image_tag("/images/pdf.png", :size => "30x30")
              - elsif documento.extension=="PNG"
                =image_tag("/images/png.png", :size => "30x30")
              - elsif documento.extension=="DOCX"
                =image_tag("/images/docx.png", :size => "30x30")
              - elsif documento.extension=="JPG"
                =image_tag("/images/jpg.png", :size => "30x30")
              - else
                =image_tag("/images/unknown.png", :size => "30x30")
            %th{:scope => "row"}=documento.titulo
            %td=documento.fecha_documento.strftime("%d/%m/%Y")
            %td=documento.peso.to_s+" KB"
            %td=documento.user.nombre
            %td
            %td
            %td=documento.extension
            %td
              %button.btn.btn-primary{:type => "button"}
                =fa_icon('file-download')

app/views/documentos/new.html.haml
:css
  choice {
    color: #333; important!
  }

:javascript
  // sugerir titulo de documento segun archivo
  $(document).ready(function(){
      $('#CustomFile').change(function(e){
          var fileName = e.target.files[0].name;
          if(fileName.indexOf(".") > 0){
            fileName = fileName.slice(0,fileName.indexOf("."));
          }
          $('#inputTitulo').val(fileName);
      });
  });
  //
  var uploadField = document.getElementById("CustomFile");

  uploadField.onchange = function() {
      maxSizeInMB = 10;
      if(this.files[0].size > 1048576 * maxSizeInMB){
         alert("El tamaño del archivo es muy grande. El tamaño máximo es " + maxSizeInMB + "MB.");
         this.value = "";
      };
      if(this.files[0].size == 0){
         alert("El archivo tiene tamaño 0. No se permite subir archivos sin contenido.");
         this.value = "";
      };
  };

.container-fluid
  .row
    =render 'layouts/alert'
  .row
    .col-md-12.mb-2{:style=>"padding: 0 2em"}
      .card
        .card-header
          %h3 Subir Nuevo Documento
        .card-body
          =form_tag("/documentos", method: "post", multipart: true) do
            .form-group.mt-3
              %label.doc-input-label{:for=>"fileInput"}
                Subir Documento
                %small
                  %span.required-true
                    *
              .custom-file#fileInput
                %input#CustomFile.custom-file-input{:required => "", :type => "file", :name=>"file", :onchange=>"relabelInput(this)"}
                %small.form-text.text-muted Tamaño máximo del documento: 10 MB.
            .form-group.mt-3
              %label.doc-input-label{:for=>"inputTitulo"}
                Título del Documento
                %small
                  %span.required-true
                    *
              %input.form-control#inputTitulo{:required => "", :type=>"text", :aria-describedby=>"tituloHelp", :placeholder=>"Ingresar Título", :name=>"title", maxlength: "255"}
            .form-group.mt-3
              %label.doc-input-label{:for=>"inputAutor"}Autor(es)
              %input.form-control#inputAutor{:type=>"text", :aria-describedby=>"autorHelp", :placeholder=>"Ingresar Autor del documento", :name=>"autor", maxlength: "255"}
            .form-group.mt-3
              %label.doc-input-label{:for => "inputDescripcion"} Descripción del Documento
              %textarea#inputDescripcion.form-control{:rows => "3", :name=>"descripcion", maxlength: "5000"}
            .form-group.mt-3


            .form-group
              .row
                .col-md-6.col-xs-12
                  %label.doc-input-label
                    Tipo de Documento
                    %small
                      %span.required-true
                        *
                  %select.js-example-basic-single{:required => "", :name => "tipo", :style=>"width:100%"}
                    %option{value: ""}
                      =""
                    -@tipos.each do |tipo|
                      %option{:value=>tipo.id}
                        =tipo.nombre
                .col-md-6.col-xs-12
                  %label.doc-input-label
                    Fecha de Creación
                  .input-group{"data-target-input" => "nearest"}
                    %input.form-control#fechaCreacion{:type=>"text", :name=>"fecha","data-provide"=>"datepicker", "data-date-end-date": "0d"}
                    -#value: "#{l(Time.zone.now, format: '%d/%m/%Y')}"
                    %span.input-group-addon{"data-target" => "#fechaCreacion"}
                      .input-group-text
                        %i.fa.fa-calendar
            .form-group
              %label.doc-input-label Áreas del Documento
              -# !!!HAY QUE METERLE DELAS LOGICAS CON JS
              %select.js-example-basic-multiple.choice{:multiple => "multiple", :name => "areas[]", :style=>"width:100%"}
                -@areas.each do |area|
                  %option{:value=>area.id}
                    =area.nombre

              -# %select.custom-select.form-control{:name=>"area"}
              -#   -@areas.each do |area|
              -#     %option{:value=>area.id}
              -#       =area.nombre
            %button.btn.btn-primary{:type=>"submit"} Subir

:javascript
  $(document).ready(function() {
    $('.js-example-basic-single').select2({
      language: "es"
    });
    $('.js-example-basic-multiple').select2({
      language: "es"
    });
  });

app/views/documentos/show.html.haml
:css
  .pl {
    padding-left: 30px; !important
  }

  .mb{
    margin-bottom: 15px;
  }
  
  .mt{
    margin-top: 8px;
  }

.container-fluid
  =render 'layouts/alert'
  .box.box-primary.color-palette-box.mt-2{:style=>"padding-top:0.5em"}
    .box-header.with-border
      .col-xs-8
        %h4
          = link_to  results_path+"?utf8=✓&search[tipo]="+@tipo.id.to_s , :target=>"_self" , :role=>"btn"  do #,:class=>"btn btn-danger mr-3"
            %button.btn.btn-sm.btn-danger{"data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Tipo de Documento"}
              = @tipo.nombre
        %h2.mb
          - if @document.extension.downcase.include? "pdf"
            %i.far.fa-file-pdf
          - elsif @document.extension.downcase.include? "png"
            %i.far.fa-file-image
          - elsif @document.extension.downcase.include? "jpg"
            %i.far.fa-file-image
          - elsif @document.extension.downcase.include? "doc"
            %i.far.fa-file-word
          - elsif @document.extension.downcase.include? "xls"
            %i.far.fa-file-excel
          - else
            %i.far.fa-file
          = "&nbsp&nbsp".html_safe + @document.titulo
        %h5
          -if current_user.puede_administrar?
            Subido por
            %span.ficha-ispan=@document.user.nombre
          - else
            Subido
          el
          %span.ficha-ispan=@document.created_at.strftime("%d/%m/%Y")
      .col-xs-4
        -# .col-1.bg-light.ficha-div.ficha-right
        -if current_user.puede_modificar_data?
          .dropdown.pull-right
            %button#dropdownMenuButton.btn.btn-default{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              =fa_icon('ellipsis-h')
            %ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenuButton"}
              %li
                %button.btn.btn-link.dropdown-item{type: "button", data: {toggle: "modal", target: "#modalEditDocument"}} Editar
              -if current_user.puede_eliminar_archivos?
                %li
                  %button.btn.btn-link.dropdown-item{type: "button", data: {toggle: "modal", target: "#modalRewriteDocument"}} Sobreescribir
                %li
                  %button.btn.btn-link.dropdown-item{type: "button", data: {toggle: "modal", target: "#modalDeleteDocument"}} Eliminar
    .box-body
      .row
        .col-md-12
          .row
            .col-md-6.pl
              - if @document.autor.present?
                %h5.mb
                  %span.ficha-bspan Autor(es):
                  =@document.autor
              - if @document.fecha_documento.present?
                %h5.mb
                  %span.ficha-bspan Fecha de Creación:
                  =@document.fecha_documento.strftime("%d/%m/%Y")
              %h5.mb
                %span.ficha-bspan Tamaño:
                -if(@document.peso < 1024)
                  =@document.peso.to_s+" bytes"
                -elsif((@document.peso)/1024.0 < 1024.0)
                  =((@document.peso)/1024.0).round(2).to_s+" KB"
                -else
                  =((@document.peso)/1024.0/1024.0).round(2).to_s+" MB"
              %h5.mb
                %span.ficha-bspan.mr-05 Áreas:
                -if @document.areas.present?
                  - @document.areas.each do |area|
                    = link_to area.full_name, results_path+"?utf8=✓&search[area]="+area.id.to_s , :target=>"_self", :role=>"btn", :class=>"label label-info mr-05"
                -else
                  %span.text-muted El documento no tiene áreas asignadas
              -if @document.extension.present?
                %h5.mb
                  %span.ficha-bspan Extensión:
                  =@document.extension.upcase
            .col-md-6
              -if @document.descripcion.present?
                %h5
                  %span.ficha-bspan.mb Descripción:
                  .well.well-sm.mt
                    =@document.descripcion
    .box.box-footer
      .col-md-2.mt
        .btn.float-right.btn-light.fav-button
          -if current_user.favoritos.any?{|f| f.documento_id == @document.id}
            .fav-link-container
              %i.fa.fa-star.text-yellow
              %a.fav-link.fav-link-marked
                Quitar de Favoritos
          -else
            .fav-link-container
              %i.far.fa-star.text-yellow
              %a.fav-link.fav-link-unmarked
                Agregar a Favoritos
      .col-md-2
        .btn.float-right.btn-light
          =fa_icon('download')
          =link_to "Descargar",documentos_descargar_path+"?data="+@document.id.to_s, :target=>"_blank", :class => "btn", :role =>"btn"



.modal.fade{id: "modalEditDocument", role: "dialog", aria: {labelledby: "modalEditDocument", hidden: "true"}}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5.modal-title{id: "modalEditDocumentLabel"}
          Editando información del documento
          %button.close{type: "button", data: {dismiss: "modal"}, aria: {label: "Cerrar"}}
            %span{aria: {hidden: "true"}} &times;
      = form_with(:url => edit_path) do
        .modal-body
          .container-fluid
            =hidden_field(:document, :archivo_documento)
            .form-group
              = label_tag('Título', nil, class: 'doc-input-label')
              %small
                %span.required-true
                  *
              = text_field(:document, :titulo, {class: 'form-control', required: true})
            .form-group
              = label_tag('Descripción', nil, class: 'doc-input-label')
              = text_area(:document, :descripcion, class: 'form-control')
            .form-group
              = label_tag('Tipo', nil, class: 'doc-input-label')
              %small
                %span.required-true
                  *
              = select(:document, :tipo_documento_id, TipoDocumento.all.collect {|p| [ p.nombre, p.id ] }, { include_blank: false }, class: 'js-example-basic-single', multiple: false, style: 'width: 100%;')
            .form-group
              = label_tag('Autor', nil, class: 'doc-input-label')
              = text_field(:document, :autor, class: 'form-control')
            .form-group
              = label_tag('Fecha de Creación', nil, class: 'doc-input-label')
              -#= date_field(:document, :fecha_documento, :required => true)
              .input-group
                %input.form-control#fechaCreacion{:type=>"text", :name=>"document[fecha_documento]","data-provide"=>"datepicker", "data-date-end-date": "0d", :value => @document.fecha_documento.present? ? @document.fecha_documento.strftime('%d/%m/%Y') : ""}
                %span.input-group-addon{"data-target" => "#fechaCreacion"}
                  .input-group-text
                    %i.fa.fa-calendar
            .form-group.mt-3
              = label_tag('Áreas', nil, class: 'doc-input-label')
              = select(:document, :area_ids, Area.all.collect {|p| [ p.nombre, p.id ] }, { include_blank: false, include_hidden: false }, {class: 'js-example-basic-multiple', multiple: true, style: 'width: 100%;'}  )
        .modal-footer
          = hidden_field(:document, :id)
          = submit_tag 'Confirmar', class: "btn btn-default"

.modal.fade{id: "modalRewriteDocument", tabindex: "-1", role: "dialog", aria: {labelledby: "modalRewriteDocument", hidden: "true"}}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5.modal-title{id: "modalRewriteDocumentLabel"}
          Sobreescribir archivo asociado al documento
          %button.close{type: "button", data: {dismiss: "modal"}, aria: {label: "Cerrar"}}
            %span{aria: {hidden: "true"}} &times;
      = form_tag(rewrite_path, method: "post", multipart: true) do
        .modal-body
          -# todo completar modal
          .container
            .form-group
              = label_tag('file', 'Ingrese la nueva versión del documento', class: 'doc-input-label')
              .custom-file#fileInput
                %input#CustomFile.custom-file-input{:required => "", :type => "file", :name=>"file", :onchange=>"relabelInput(this)"}
                %label.custom-file-label{:for => "validatedCustomFile"} ---
                %small.form-text.text-muted Tamaño máximo del documento: 10 Mb.
        .modal-footer
          = hidden_field(:document, :id)
          = submit_tag 'Confirmar', class: "btn btn-default"

.modal.fade{id: "modalDeleteDocument", tabindex: "-1", role: "dialog", aria: {labelledby: "modalDeleteDocument", hidden: "true"}}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5.modal-title{id: "modalDeleteDocumentLabel"}
          Eliminar documento
          %button.close{type: "button", data: {dismiss: "modal"}, aria: {label: "Cerrar"}}
            %span{aria: {hidden: "true"}} &times;
      .modal-body
        %p
          ¿Está seguro de que desea
          %b eliminar
          este Documento?
      .modal-footer
        = form_with(:url => delete_path) do
          = hidden_field(:document, :id)
          = submit_tag 'Eliminar', class: "btn btn-danger"
:javascript
  $(document).ready(function() {
    $('.js-example-basic-single').select2({
      dropdownParent: "#modal-container"
    });
    $('.js-example-basic-multiple').select2({
      language: "es"
      width: 'resolve'
    });
  });