config/routes.rb
Rails.application.routes.draw do
  # usuarios y log in
  devise_for :users
  get 'user/log_in'
  get 'user/log_in_as_user'
  get 'user/log_out'
  get 'user/sin_permisos'
  post 'externo', to: 'user#externo'
  get 'user/authenticated'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'documentos/descargar', to: 'documentos#descargar'
  resources :documentos

  get 'favoritos', to: 'favoritos#show'
  post 'add_favorito', to: 'documentos#add_favorite'
  post 'remove_favorito', to: 'documentos#remove_favorite'

  get 'admin', to: 'admin#index'
  get 'admin/usuarios', to: 'admin#index', :as => 'admin_usuarios'
  get 'admin/tipos', to: 'admin#index', :as => 'admin_tipos'
  get 'admin/areas', to: 'admin#index', :as => 'admin_areas'
  get 'admin/actividad', to: 'admin#index', :as => 'admin_actividad'

  post 'admin/create_tipo', to: 'admin#create_tipo'
  post 'admin/update_tipo', to: 'admin#update_tipo'
  post 'admin/delete_tipo', to: 'admin#delete_tipo'

  post 'admin/create_area', to: 'admin#create_area'
  post 'admin/update_area', to: 'admin#update_area'
  post 'admin/delete_area', to: 'admin#delete_area'

  post 'admin/update_usuario', to: 'admin#update_usuario'
  get 'home', to: 'home#index'

  get 'search/advanced', to: 'busquedas#advanced'
  get 'results', to: 'busquedas#search'
  get 'search', to: 'busquedas#normal_search'

  post 'delete', to: 'documentos#delete'
  post 'edit', to: 'documentos#edit'
  post 'rewrite', to: 'documentos#rewrite'

  # Es necesario que la root esté seteada para el tema de usuarios
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise
  has_many :documentos
  has_many :favoritos
  has_many :documentos_favoritos, -> { order 'favoritos.id desc' }, through: :favoritos, source: :documento
  has_many :user_descarga_documentos
  has_many :documentos_descargados, -> { order 'user_descarga_documentos.id desc'}, through: :user_descarga_documentos, source: :documento

  enum permiso: [:Sin_Permisos, :Visitante, :Asistente, :Coordinador, :Administrador]

  def puede_ver_sitio?
    self.Visitante? or self.Asistente? or self.Coordinador? or self.Administrador?
  end

  def puede_modificar_data?
    self.Asistente? or self.Coordinador? or self.Administrador?
  end

  def puede_subir_archivos?
    self.Asistente? or self.Coordinador? or self.Administrador?
  end

  def puede_eliminar_archivos?
    self.Coordinador? or self.Administrador?
  end

  def puede_sobreescribir_archivos?
    self.Coordinador? or self.Administrador?
  end

  def puede_administrar?
    self.Administrador?
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :externo
  @@log_in_placeholder_esta_habilidado = false

  def log_in
  end

  def log_out
    sign_out :user
    redirect_to user_log_in_path
  end

  def log_in_as_user
    if not Rails.env.development?
      redirect_to root_path
      return
    end
    tipo = params[:tipo]
    user = User.find_by nombre: "Usuario #{tipo}"
    if not user.present?
      user = User.new
      user.nombre = "Usuario #{tipo}"
      user.rut = "11.111.111-1"
      user.permiso = tipo
      user.save!
    end
    sign_in(user, scope: :user)
    if tipo == "Administrador"
      redirect_to admin_path
    else
      redirect_to root_path
    end
  end

  def sin_permisos
  end

  DATA_PROVIDER = 'https://www.u-cursos.cl/upasaporte/?servicio=repodcc&ticket=%s'
  REDIRECT_URL = 'http://docs.dcc.uchile.cl/user/authenticated?sessid='
  @@SESSIONS = {}

  def externo
    data = Net::HTTP.get(URI(sprintf(DATA_PROVIDER, params[:ticket])))
    if not data or data.length <= 2
      render :plain => 'Surgió un error ', :status => 400
      return
    end
    uuid = SecureRandom.uuid;
    @@SESSIONS[uuid] = data;
    redirect_url_to_return = REDIRECT_URL+uuid
    render plain: redirect_url_to_return
  end

  def authenticated
    raw_data = @@SESSIONS[params[:sessid]]
    if not raw_data.present?
      render :text => 'error', :status => 400
      return
    end
    user_data = JSON.parse(raw_data)
    rut = user_data["pers_id"]
    user = User.find_by rut: rut
    if not user.present?
      user = User.new
      user.nombre = user_data["alias"]
      user.rut = rut
      user.permiso = :Sin_Permisos
      user.save!
    end
    sign_in(user, scope: :user)
    @@SESSIONS.delete(params[:sessid])
    if user.permiso == :Administrador
      redirect_to admin_path
    else
      redirect_to root_path
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/log_in.html.haml
:css
  .mt {
    margin-top: 20px;
  }

  .mb {
    margin-bottom: 10px;
  }

  .center {
    text-align:center;
    margin:auto;
  }

.container
  .row
    .col-sm-2
    .col-sm-8
      .panel.panel-default.mt
        .panel-body
          .center
            %h2 Repositorio de Documentos del DCC
            .mt
              %script{:language => "JavaScript", :src => "https://www.u-cursos.cl/upasaporte/javascript?servicio=repodcc"}
            - if Rails.env.development?  
              %h2.card-title.text-center.center-block Log In placeholder
              .row.py-3
                .col-xs-12.mb
                  .center
                  = link_to "Log in como 'Sin permisos'", user_log_in_as_user_path(tipo: :Sin_Permisos), method: :get, :class => "btn btn-primary"
                .col-xs-12.mb
                  .center
                  = link_to "Log in como Visitante", user_log_in_as_user_path(tipo: :Visitante), method: :get, :class => "btn btn-primary"
                .col-xs-12.mb
                  .center
                  = link_to "Log in como Asistente", user_log_in_as_user_path(tipo: :Asistente), method: :get, :class => "btn btn-primary"
                .col-xs-12.mb
                  .center
                  = link_to "Log in como Coordinador", user_log_in_as_user_path(tipo: :Coordinador), method: :get, :class => "btn btn-primary"
                .col-xs-12.mb
                  .center
                  = link_to "Log in Administrador", user_log_in_as_user_path(tipo: :Administrador), method: :get, :class => "btn btn-primary"
    .col-sm-2

app/views/user/sin_permisos.html.haml
:css
  .mt {
    margin-top: 20px;
  }

  .center {
    text-align:center;
    margin:auto;
  }

.container
  .row
    .col-sm-2
    .col-sm-8.mx-auto
      .panel.panel-default.mt
        .panel-body
          %h1 Hola!
          %h3 Gracias por acceder al repositorio de documentos del DCC.
          %h4 Para tener acceso a los documentos del repositorio, contacta al administrador de la plataforma en apps@dcc.uchile.cl con tu nombre y RUT.
          .center
            = link_to "Cerrar Sesión", user_log_out_path, method: :get, :class => "btn btn-primary"
    .col-sm-2